---
- name: install the lsyncd package
  apt:
    pkg: lsyncd
    state: present
    update_cache: no

- name: create config directories
  file:
    name: /etc/lsyncd/conf.d/
    state: directory
    owner: root
    group: root
    mode: 0750

- name: template config snippet with the settings section
  template:
    src: templates/etc/lsyncd/conf.d/settings.conf.lua.j2
    dest: /etc/lsyncd/conf.d/settings.conf.lua
    owner: root
    group: root
    mode: 0640
  notify: restart lsyncd

- name: template all sync config snippets
  template:
    src: templates/etc/lsyncd/conf.d/sync.conf.lua.j2
    dest: "/etc/lsyncd/conf.d/{{ lsyncd_sync_configuration['name'] }}.conf.lua"
    owner: root
    group: root
    mode: 0640
  with_items: "{{ lsyncd_sync_configurations }}"
  loop_control:
    loop_var: lsyncd_sync_configuration
  notify: restart lsyncd

- name: assemble the config snippets in /etc/lsycnd/conf.d/
  assemble:
    src: /etc/lsyncd/conf.d/
    dest: /etc/lsyncd/lsyncd.conf.lua
    owner: root
    group: root
    mode: 0640
    delimiter: ""
  notify: restart lsyncd

- name: set /proc/sys/fs/inotify/max_user_watches
  sysctl:
    name: fs.inotify.max_user_watches
    value: "{{ lsyncd_inotify_max_user_watches }}"
    sysctl_set: yes
    state: present
    reload: yes
  when: lsyncd_inotify_max_user_watches is defined
